# NumPy Primer
---
Numpy is a powerful add-on package to Python for handling arrays. Below are the most commonly used features.

Table of Contents:
1. [Importing numpy](#section1)
2. [Creating numpy arrays](#section2)
3. [Data types](#section3)
4. [Array properties](#section4)
5. [Indexing and slicing](#section5)
6. [Reshaping and resizing](#section6)
7. [Stacking and splitting](#section7)
8. [Creating meshgrids](#section8)

REFERENCES:
- [1] Johansson, *Numerical Python: A Practical Techniques Approach for Industry*

## 1. Importing numpy <a id='section1'></a>
Before using the various commands from the numpy module, you first have to load it.

In [1]:
# load all numpy commands all at once (not recommended)
#from numpy import *

In [1]:
# introduce an alias for the numpy namespace (recommended)
import numpy as np

## 2. Creating numpy arrays <a id='section2'></a>
There are multiple ways of creating ndarrays.

### array( )

array() allows you to explicitly define an array by specifying all of its elements. This can be useful for smallish arrays, but it does not scale well. (You wouldn't want to specify all 100 elements of a 10 x 10 array by hand! Much less, a 100 x 100 array.)

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### arange( )

arange() creates an array from a given starting value, up to (but not including) a given end value, in a given stepsize increment. 

NOTE #1: the end value is NOT included in the array. 

NOTE #2: start value is optional, default is 0

NOTE #3: stepsize is super-optional, default is 1

In [6]:
# 10-element array, with default start value (0) and default stepsize (1)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# array from 2 to 9, with default stepsize (1)
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# array from 0 to 9, with stepsize of 3
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [9]:
# array from 10 to 1, in decreasing order, stepsize of 3
np.arange(10, 0, -3)

array([10,  7,  4,  1])

In [10]:
# 2D array
np.array([np.arange(10),np.arange(10)])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### linspace( )

linspace() creates an array from a given starting value, up to (and including) a given end value, with a given number of points. 

NOTE #1: the end value IS included in the array.

NOTE #2: start value is NOT optional.

NOTE #3: number of points is optional, default is 50.

In [11]:
# 0 to 10, a total of 50 points (default)
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
# 0 to 10, a total of 3 points
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
# decreasing order
np.linspace(10, 0, 3)

array([10.,  5.,  0.])

**NOTE: linspace() creates an array using a fixed number of POINTS, not a fixed number of STEPS. For N steps, you need N+1 points, in order to account for the start and end points, as the next example shows**

In [14]:
# 0 to 10, with stepsize 1 (10 steps, 11 points)
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### logspace( )

Like linspace(), except increments are based on a log scale, as opposed to a linear scale.

In [15]:
# 1 to 100, log scale base-10 (default), a total of 50 points (default)
np.logspace(0, 2)

array([  1.        ,   1.09854114,   1.20679264,   1.32571137,
         1.45634848,   1.59985872,   1.75751062,   1.93069773,
         2.12095089,   2.32995181,   2.55954792,   2.8117687 ,
         3.0888436 ,   3.39322177,   3.72759372,   4.09491506,
         4.49843267,   4.94171336,   5.42867544,   5.96362332,
         6.55128557,   7.19685673,   7.90604321,   8.68511374,
         9.54095476,  10.48113134,  11.51395399,  12.64855217,
        13.89495494,  15.26417967,  16.76832937,  18.42069969,
        20.23589648,  22.22996483,  24.42053095,  26.82695795,
        29.47051703,  32.37457543,  35.56480306,  39.06939937,
        42.9193426 ,  47.14866363,  51.79474679,  56.89866029,
        62.50551925,  68.6648845 ,  75.43120063,  82.86427729,
        91.0298178 , 100.        ])

In [16]:
# 1 to 100, log scale base-10 (default), a total of 10 points
np.logspace(0, 2, 10)

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [17]:
# decreasing order
np.logspace(2, 0, 10)

array([100.        ,  59.94842503,  35.93813664,  21.5443469 ,
        12.91549665,   7.74263683,   4.64158883,   2.7825594 ,
         1.66810054,   1.        ])

In [18]:
# 1 to 4, log scale base-2, a total of 50 points (default)
np.logspace(0, 2, base=2)

array([1.        , 1.02869573, 1.05821491, 1.08858117, 1.1198188 ,
       1.15195282, 1.18500895, 1.21901365, 1.25399415, 1.28997843,
       1.3269953 , 1.36507441, 1.40424622, 1.44454209, 1.48599429,
       1.52863599, 1.57250132, 1.61762539, 1.66404434, 1.71179531,
       1.76091654, 1.81144733, 1.86342814, 1.91690058, 1.97190744,
       2.02849277, 2.08670186, 2.1465813 , 2.20817903, 2.27154434,
       2.33672798, 2.4037821 , 2.47276039, 2.54371806, 2.61671192,
       2.69180039, 2.76904357, 2.84850331, 2.9302432 , 3.01432868,
       3.10082705, 3.18980756, 3.28134142, 3.37550192, 3.47236443,
       3.57200647, 3.67450782, 3.77995051, 3.88841897, 4.        ])

### zeros( )

Creates an array filled with zeros.

In [19]:
# 1D array of zeros
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# 2D array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 3D array of zeros
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### ones( )

Creates an array filled with ones.

In [22]:
# 1D array of ones
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# 2D array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# 3D array of ones
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### full( )

Creates an array filled with a given value.

In [25]:
# 1D constant array
np.full((2), 2.25)

array([2.25, 2.25])

In [26]:
# 2D constant array
np.full((2,3), 2.25)

array([[2.25, 2.25, 2.25],
       [2.25, 2.25, 2.25]])

In [27]:
# 3D constant array
np.full((3,3,3), 2.25)

array([[[2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25]],

       [[2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25]],

       [[2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25]]])

### empty( ), copy( ) and fill( )

In [28]:
a = np.empty((5,3)) # create an empty array, filled with random junk (DANGEROUS!)
b = np.copy(a)      # copy an array
b.fill(2.25)        # fill a pre-defined array with some value
a, b

(array([[6.92926053e-310, 2.75418278e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 6.32404027e-322]]),
 array([[2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25],
        [2.25, 2.25, 2.25]]))

### zeros_like( )

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### ones_like( )

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### diag( )

In [31]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### eye( )

In [32]:
# square array (default), of size 3, ones along the diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# rectangular
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
# square array, ones offset to the right by 2
np.eye(5, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
# square array, ones offset to the left by 2
np.eye(5, 5, -2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## 3. Data types <a id='section3'></a>

### type( )

In [36]:
# example of an integer, type = int
type(3)

int

In [37]:
# example of a floating decimal point number, type = float
type(3.)

float

In [38]:
# example of a complex floating point number, type = complex
type(3. + 0j)

complex

### data types for ndarrays (dtype) 

In [39]:
# an array of integers, created using array()
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [40]:
# an array of floats, created using array()
b = np.array([1, 2, 3], dtype=float)
b.dtype

dtype('float64')

In [41]:
# an array of floats, created using arange()
np.arange(3, dtype=float)

array([0., 1., 2.])

In [42]:
# an array of integers, created using linspace()
np.linspace(0, 10, 4, dtype=int)

array([ 0,  3,  6, 10])

In [43]:
# an array of complex numbers, created using ones()
np.ones(4, dtype=complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

## 4. Array properties <a id='section4'></a>

### .dtype

In [44]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

### .shape

In [45]:
a = np.ones((3,4,5))
a.shape

(3, 4, 5)

### .ndim

In [46]:
# number of dimensions, or axes
a = np.ones((5,5,5))
a.ndim

3

### .size

In [47]:
# total number of elements
a = np.ones((5,5,5))
a.size

125

### .nbytes

In [48]:
# total amount of memory, in bytes
a = np.ones((5,5,5))
a.nbytes

1000

## 5. Indexing and Slicing <a id='section5'></a>

### indexing for a 1D array

In [49]:
# sample 1D array
a = np.arange(1, 11, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# indices start from 0
print(a[0])
print(a[1])
print(a[2])

1
2
3


In [51]:
# negative indices start from the end
print(a[-1])
print(a[-2])
print(a[-3])

10
9
8


In [52]:
# zero is un-signed (-0 = +0 = 0)
print(a[-0])
print(a[+0])
print(a[0])

1
1
1


### indexing for a 2D array

In [53]:
# sample 2D array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
print(b[0,0])
print(b[1,1])
print(b[2,0])
print(b[-1,-1])

1
5
7
9


### slicing a 1D array

In [55]:
# sample 1D array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[:3]

array([0, 1, 2])

In [58]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [60]:
a[3:9:2]

array([3, 5, 7])

### slicing a 2D array

In [61]:
# sample 2D array
b = np.array([np.arange(0,10),np.arange(10,20), np.arange(20,30), np.arange(30,40)])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [62]:
b[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [63]:
b[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [64]:
b[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [65]:
b[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [66]:
b[1:3, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
b[1:3, :4]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [68]:
b[1:3, 4:]

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [69]:
b[1:3, 4:7]

array([[14, 15, 16],
       [24, 25, 26]])

In [70]:
b[:, 4:7]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [71]:
b[:2, 4:7]

array([[ 4,  5,  6],
       [14, 15, 16]])

In [72]:
b[2:, 4:7]

array([[24, 25, 26],
       [34, 35, 36]])

In [73]:
b[1:3, 4:7]

array([[14, 15, 16],
       [24, 25, 26]])

In [74]:
b[1:4:2, 1:5:2]

array([[11, 13],
       [31, 33]])

**WARNING: slicing creates a view, not a copy**

In [75]:
# define array c, a copy of a from above
c = np.copy(a)
print('original c = \n', c, '\n')

# define array d, a slice of c
d = c[2:6]
print('original d = \n', d, '\n')

# alter the contents of c
c[:4] = 0
print('new c = \n', c, '\n')

# print d again to see if its contents have changed
print('new? d = \n', d, '\n')

original c = 
 [0 1 2 3 4 5 6 7 8 9] 

original d = 
 [2 3 4 5] 

new c = 
 [0 0 0 0 4 5 6 7 8 9] 

new? d = 
 [0 0 4 5] 



## 6. Reshaping and Resizing <a id='section6'></a>

In [76]:
# sample 2D array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### reshape( )

In [77]:
b = np.copy(a)
np.reshape(b, (4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
c = np.copy(a)
c.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**NOTE: reshape( ) creates a copy, without affecting the original**

In [79]:
# define array b, a copy of a from above
b = np.copy(a)
print('original b = \n', b, '\n')

# define array c, reshape of b
c = b.reshape(4,3)
print('original c = \n', c, '\n')

# print b again to see if its contents have changed
print('new? b = \n', b, '\n')

original b = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

original c = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

new? b = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



### resize( )

In [80]:
b = np.copy(a)
np.resize(b, (4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
c = np.copy(a)
c.resize(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**NOTE: resize( ) creates a copy, without affecting the original**

In [82]:
# define array b, a copy of a from above
b = np.copy(a)
print('original b = \n', b, '\n')

# define array c, resize of b
c = np.resize(b, (4,3))
print('original c = \n', c, '\n')

# print b again to see if its contents have changed
print('new? b = \n', b, '\n')

original b = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

original c = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

new? b = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



### ndarray.resize( )

In [83]:
b = np.copy(a)
np.ndarray.resize(b, (4,3))
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**NOTE: ndarray.resize( ) acts on the original**

In [84]:
# define array b, a copy of a from above
b = np.copy(a)
print('original b = \n', b, '\n')

# define array c, ndarray.resize of b
np.ndarray.resize(b, (4,3))
print('original c = \n', b, '\n')

# print b again to see if its contents have changed
print('new? b = \n', b, '\n')

original b = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

original c = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

new? b = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 



## 7. Stacking and Splitting <a id='section7'></a>

### stacking 1D arrays

In [85]:
# sample 1D arrays
a = np.ones(2)
b = 2*a
print('a = ', a)
print('b = ', b)

a =  [1. 1.]
b =  [2. 2.]


In [86]:
np.vstack((a,b))

array([[1., 1.],
       [2., 2.]])

In [87]:
np.hstack((a,b))

array([1., 1., 2., 2.])

In [88]:
np.dstack((a,b))

array([[[1., 2.],
        [1., 2.]]])

In [89]:
np.row_stack((a,b))

array([[1., 1.],
       [2., 2.]])

In [90]:
np.column_stack((a,b))

array([[1., 2.],
       [1., 2.]])

In [91]:
np.concatenate((a,b), axis=0)

array([1., 1., 2., 2.])

### stacking 2D arrays

In [92]:
# sample 2D arrays
a = np.ones((2,2))
b = 2*a
print('a = \n', a, '\n')
print('b = \n', b, '\n')

a = 
 [[1. 1.]
 [1. 1.]] 

b = 
 [[2. 2.]
 [2. 2.]] 



In [93]:
np.vstack((a,b))

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.]])

In [94]:
np.hstack((a,b))

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.]])

In [95]:
np.dstack((a,b))

array([[[1., 2.],
        [1., 2.]],

       [[1., 2.],
        [1., 2.]]])

In [96]:
np.row_stack((a,b))

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.]])

In [97]:
np.column_stack((a,b))

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.]])

In [98]:
np.concatenate((a,b), axis=0)

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.]])

In [99]:
np.concatenate((a,b), axis=1)

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.]])

### splitting 1D arrays

### splitting 2D arrays

## 8. Creating meshgrids <a id='section8'></a>

In [100]:
# create meshgrid array
x = np.arange(0,10,1)
y = np.arange(0,20,2)
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
        [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
        [16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
        [18, 18, 18, 18, 18, 18, 18, 18, 18, 18]]))